### ISSUE TITLE
gotty arguments need order

### ISSUE THREAD

**Issue by huiwq1990** [sorenisanerd/gotty#54]
# When file a bug report (see below for feature requests)

Please answer these quesions for a bug report. Thanks!

### What version of GoTTY are you using (`gotty --version`)?

latest verision, build myself.

### What operating system and browser are you using?

linux

### What did you do?

```shell
[root@docker-desktop ~]# /usr/bin/gotty --port 9090 --address 0.0.0.0 --permit-write true --permit-arguments true ssh
2022/11/03 03:48:01 GoTTY is starting with command: true --permit-arguments true ssh
2022/11/03 03:48:01 Permitting clients to write input to the PTY.
2022/11/03 03:48:01 HTTP server is listening at: http://[::]:9090/
2022/11/03 03:48:01 Alternative URL: http://127.0.0.1:9090/
2022/11/03 03:48:01 Alternative URL: http://[::1]:9090/
2022/11/03 03:48:01 Alternative URL: http://192.168.65.3:9090/
2022/11/03 03:48:01 Alternative URL: http://[fe80::50:ff:fe00:1]:9090/
```

```shell
[root@docker-desktop ~]# /usr/bin/gotty --port 9090 --address 0.0.0.0 --permit-arguments true --permit-write true ssh
2022/11/03 03:48:53 GoTTY is starting with command: true --permit-write true ssh
2022/11/03 03:48:53 HTTP server is listening at: http://[::]:9090/
2022/11/03 03:48:53 Alternative URL: http://127.0.0.1:9090/
2022/11/03 03:48:53 Alternative URL: http://[::1]:9090/
2022/11/03 03:48:53 Alternative URL: http://192.168.65.3:9090/
2022/11/03 03:48:53 Alternative URL: http://[fe80::50:ff:fe00:1]:9090/
```

### What did you expect to see?

all command should output:
```
2022/11/03 03:48:01 Permitting clients to write input to the PTY.
```

### What did you see instead?

The second command not enable `permit-write`.

# When file a new feature proposal

Could we use cobra as out cli library? It's more easy process command flages.

https://github.com/spf13/cobra

**Comment by sorenisanerd** [comment]
Your problem is the fact that you're adding `true` to your command line. It is simply `--permit-arguments`, not `--permit-arguments true`. Same for `--permit-write`. The first non-option argument to gotty marks the start of the command that gotty will run for each web client. In your example logs, you can see that the command it invokes is `true --permit-arguments true ssh` and `true --permit-write true ssh`.

Just run `gotty --port 9090 --address 0.0.0.0 --permit-arguments --permit-write ssh` and you should be good to go.
